# This configuration is intended for development purpose, it's your responsibility to harden it for production
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-api
        image: moreskovic/flask-demo-api:alpha
        ports:
          - containerPort:
