# This configuration is intended for development purpose, it's your responsibility to harden it for production
# In production environment it's not recommended to use NodePort
apiVersion: v1
kind: Service
metadata:
  name: flask-np
spec:
  type: NodePort
  selector:
    app: flask_appp
  ports:
    - port: 8084
      targetPort:
      nodePort: 30007